name: Docker build

on:
  pull_request:
    paths:
      - 'Dockerfile'
    branches:
      - 'master'

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
    steps:
    - uses: actions/checkout@v2
    - name: Build Docker image
      uses:  docker/build-push-action@v1
      with:
        repository: gqcg/bootcamp
        tags: latest
        registry: docker.io
        dockerfile: Dockerfile
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        push: false
    